services:
  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.${DOCKER_ENV:-dev}.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
  backend:
    container_name: backend
    build:
      context: ../services/backend
      dockerfile: Dockerfile
      target: ${DOCKER_ENV:-dev}
    restart: always
    ports:
      - "4983:4983"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - DB_FILE_NAME=${DB_FILE_NAME:-file:./database/app.db}
    volumes:
       - ../services/backend/srcs:/app/services/backend/srcs
       - ../services/backend/database:/app/services/backend/database
       - ../services/backend/drizzle:/app/services/backend/drizzle
       - /app/services/backend/node_modules  # Anonymous volume to preserve node_modules
  frontend:
    container_name: frontend
    build:
      context: ../services/frontend
      dockerfile: Dockerfile
      target: ${DOCKER_ENV:-dev}
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    expose:
      - "5173" # Vite dev server
    volumes:
      - ../services/frontend/srcs:/app/services/frontend/srcs
      - ../services/frontend/index.html:/app/services/frontend/index.html:ro
      - ../services/frontend/vite.config.ts:/app/services/frontend/vite.config.ts:ro
      - /app/services/frontend/node_modules  # Anonymous volume to preserve node_modules
