services:
  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    ports:
      - "8080:80" # For development maybe remove this at the end
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: services/backend/Dockerfile
    ports:
      - "4983:4983"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # - DATA_DIR=/data
      - DB_FILE_NAME=$DB_FILE_NAME
    volumes:
      - ../services/backend/database:/app/database
  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: services/frontend/Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - "80" # For development maybe remove this at the end
