services:
  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.${DOCKER_ENV:-dev}.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: services/backend/Dockerfile
      target: ${DOCKER_ENV:-dev}
    working_dir: /app/services/backend
    ports:
      - "4983:4983" # for drizzle studio (db)
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - DB_FILE_NAME=${DB_FILE_NAME:-file:./database/app.db}
    volumes:
      - ../services/backend:/app/services/backend
  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: services/frontend/Dockerfile
      target: ${DOCKER_ENV:-dev}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    expose:
      - "5173" # Vite dev server
    volumes:
      - ../services/frontend/srcs:/app/services/frontend/srcs
      - ../services/frontend/index.html:/app/services/frontend/index.html:ro
      - ../services/frontend/vite.config.ts:/app/services/frontend/vite.config.ts:ro
