export { Home } from "./home/Home";
export { NotFound } from "./NotFound";
export { Pong } from "./pong/pong";
export { Settings } from "./settings/Settings";
export { UserProfile } from "./profile/UserProfile";
export { Achievement } from "./profile/Achievements";
export { Lobby } from "./pong/Lobby";
export { Login } from "./auth/Login";
export { Signup } from "./auth/SignUp";
